
name: 'Setup and run tests'
description: 'Sets up PHP and Composer, and runs tests.'

inputs:
  php-version:
    description: 'The PHP version you wish to use.'
    required: true
  php-extensions:
    description: 'The PHP extensions you want to install.'
    required: false
    default: 'dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo'
  composer-stability:
    description: '.'
    required: false
    default: 'prefer-stable'
  exclude-groups:
    description: 'The test groups you want to exclude.'
    required: false
    default: false
  coverage:
    description: 'The coverage driver to use.'
    required: false
    default: 'none'

runs:
  using: 'composite'
  steps:
    - name: 'Get PHP extension cache hash'
      id: get-cache-hash
      shell: bash
      env:
        PHP_EXTENSIONS: ${{ inputs.php-extensions }}
      run: echo hash=$(echo "$PHP_EXTENSIONS" | md5sum | awk '{print $1}') >> $GITHUB_OUTPUT

    - name: Get PHP extension cache hash
      id: extensions-cache-hash
      env:
        PHP_EXTENSIONS: ${{ inputs.php-extensions }}
      run: echo hash=$(echo "$PHP_EXTENSIONS" | md5sum | awk '{print $1}') >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup cache environment
      id: extensions-cache
      uses: shivammathur/cache-extensions@v1
      if: inputs.php-extensions == true
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        key: php-extensions-${{ steps.extensions-cache-hash.outputs.hash }}

    - name: Cache extensions
      uses: actions/cache@v4
      if: inputs.php-extensions == true
      with:
        path: ${{ steps.extensions-cache.outputs.dir }}
        key: ${{ steps.extensions-cache.outputs.key }}
        restore-keys: ${{ steps.extensions-cache.outputs.key }}

    - name: Setup PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        coverage: ${{ inputs.coverage }}

    - name: Get Composer cache dir
      id: composer-cache-dir
      run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}

    - name: Install dependencies
      run: composer update --${{ inputs.composer-stability }} --prefer-dist --no-interaction
      shell: bash

    - name: Execute tests
      run: vendor/bin/pest
      shell: bash
      if: inputs.coverage == 'none' && inputs.exclude-groups == 'false'

    - name: Execute tests
      run: vendor/bin/pest --exclude-group=${{ inputs.exclude-groups }}
      shell: bash
      if: inputs.coverage == 'none' && inputs.exclude-groups != 'false'

    - name: Execute tests with coverage
      run: vendor/bin/pest --coverage-clover=build/logs/clover.xml
      shell: bash
      if: inputs.coverage != 'none'
